/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DisksImport } from './routes/disks'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const DisksRoute = DisksImport.update({
  id: '/disks',
  path: '/disks',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/disks': {
      id: '/disks'
      path: '/disks'
      fullPath: '/disks'
      preLoaderRoute: typeof DisksImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/disks': typeof DisksRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/disks': typeof DisksRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/disks': typeof DisksRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/disks'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/disks'
  id: '__root__' | '/' | '/disks'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DisksRoute: typeof DisksRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DisksRoute: DisksRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/disks"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/disks": {
      "filePath": "disks.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
